# -*- coding: utf-8 -*-
"""TugasBesar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JFuO_keEBhDzMGy8zV7p9CTjQ83bZ_8o

**TUGAS BESAR VISUALISASI DATA**
1. Adhe Akram Azhari 1301194063
2. Retno Diah Ayu Ningtias 1301194460
"""

import numpy as np
import pandas as pd
from bokeh.io import output_file, output_notebook
from bokeh.plotting import figure, show, curdoc
from bokeh.models import ColumnDataSource, HoverTool, GroupFilter,CDSView, DateRangeSlider, CustomJS,Dropdown, Range1d
from bokeh.layouts import row, column, gridplot, layout
from bokeh.models.widgets import Tabs, Panel
from bokeh.resources import INLINE

output_notebook(resources=INLINE)

data = pd.read_csv('data/covid-variants.csv', parse_dates=['date'])
data

"""### MENAMPILKAN KASUS OMICRON DI ANGOLA DENGAN HOVERTOOL"""

Omicron = (data[(data['location'] == 'Angola') | (data['location'] == 'Argentina') ]
               .loc[:, ['date', 'location', 'variant','num_sequences_total']]
               .sort_values(['date']))


dataAngola = Omicron[Omicron['location'] == 'Angola']


dataAngola_cds = ColumnDataSource(dataAngola)


output_file('OmicronAngola.html',
            title='Plot kasus Omicron di Angola')



select_tools = ['box_select', 'lasso_select', 'poly_select', 'tap', 'reset']


fig = figure(x_axis_type='datetime',
             plot_height=500,
             plot_width=500,
             x_axis_label='date',
             y_axis_label='Jumlah kasus Omicron',
             title='Plot kasus Omicron di Angola',
             toolbar_location='below',
             tools=select_tools)

fig.square(x='date',
           y='num_sequences_total',
           source=dataAngola_cds,
           color='royalblue',
           selection_color='deepskyblue',
           nonselection_color='lightgray',
           nonselection_alpha= 0.3)

tooltips = [
            ('location','@location'),
            ('date', '@date'),
            ('variant', '@variant'),
            ('Total Kasus Omicron','@num_sequences_total'),
           ]


fig.add_tools(HoverTool(tooltips=tooltips))

show(fig)
curdoc().add_root(fig)

"""### MENAMPILKAN VARIAN OMICRON DI ANGOLA DAN ARGENTINA DENGAN FITUR HIDE AND MUTE

"""

dataAngola1 = Omicron[Omicron['location'] == 'Angola']
dataArgentina1 = Omicron[Omicron['location'] == 'Argentina']

frames = [dataAngola1, dataArgentina1]
datasource = pd.concat(frames)
data_Source = ColumnDataSource(datasource)
datasource

Angola_view = CDSView(source=data_Source,
                      filters=[GroupFilter(column_name='location', 
                                           group='Angola')])

Argentina_view = CDSView(source=data_Source,
                      filters=[GroupFilter(column_name='location', 
                                           group='Argentina')])

fig = figure(x_axis_type='datetime',
             plot_height=1000,
             plot_width=1200,
             x_axis_label='Date',
             y_axis_label='Omicron',
             title='Plot kasus varian virus omicron',
             toolbar_location='below',
             tools=select_tools)


output_file('DataKasusvarian''.html',
            title='Kasus varian virus omicron di Angola dan Argentina')


figuree = {
    'x_axis_type': 'datetime',
    'plot_width': 400,
    'x_axis_label': 'date',
    'toolbar_location': None,
}
circle = {
    'x': 'date',
    'y': 'num_sequences_total',
    'source': data_Source,
    'size': 12,
    'alpha': 0.7,
}
Angola = {
    'view': Angola_view,
    'color': '#002859',
    'legend': 'Angola'
}
Argentina = {
    'view': Argentina_view,
    'color': '#FFC324',
    'legend': 'Argentina'
}


hide_fig = figure(**figuree,
                  title='Klik label untuk menyembunyikan data',y_axis_label='Rebounds')
hide_fig.circle(**circle, **Angola)
hide_fig.circle(**circle, **Argentina)

mute_fig = figure(**figuree, title='Klik label untuk mute data',y_axis_label='Rebounds')
mute_fig.circle(**circle, **Angola,
                muted_alpha=0.05)
mute_fig.circle(**circle, **Argentina,
                muted_alpha=0.05)

hide_fig.legend.click_policy = 'hide'
mute_fig.legend.click_policy = 'mute'


show(row(hide_fig, mute_fig))
curdoc().add_root(hide_fig)
curdoc().add_root(mute_fig)
